In [1]:
import torch
import torch_geometric as pyg

Pytorch-Geometric

In [62]:
""" House graph:

    node index:
       4
      / \
     3---2
     |   |
     0---1

    feature value:
        5.4
       /   \
     3.2---4.3
     |      |
     1.0---2.1

    
    edge feature value
       .
      4 5
     . 6 .
     11  8
     . 7 .
"""

x = torch.tensor([[1.0], [2.1], [3.2], [4.3], [5.4]], dtype=torch.float)
edge_index = torch.tensor([[0, 1, 0, 3, 1, 2, 2, 3, 2, 4, 3, 4],
                           [1, 0, 3, 0, 2, 1, 3, 2, 4, 2, 4, 3]], dtype=torch.long)
edge_attr = torch.tensor([[7], [7], [11], [11], [8], [8], [6], [6], [5], [5], [4], [4]], 
                            dtype=torch.float)
y = torch.tensor([12.345], dtype=torch.float)
house = pyg.data.Data(x=x, 
                      edge_index=edge_index, 
                      edge_attr=edge_attr,
                      y=y)

In [63]:
house

Data(edge_attr=[12, 1], edge_index=[2, 12], x=[5, 1], y=[1])

In [64]:
"""Square graph:

     node index:
     3---2
     |   |
     0---1

     feature value:
     4.4---3.3
     |      |
     1.1---2.2

     . 8 .
     90  7
     . 6 .
"""

x = torch.tensor([[1.1], [2.2], [3.3], [4.4]], dtype=torch.float)
edge_index = torch.tensor([[0, 1, 0, 3, 1, 2, 2, 3],
                           [1, 0, 3, 0, 2, 1, 3, 2]], dtype=torch.long)
edge_attr = torch.tensor([[6], [6], [90], [90], [7], [7], [8], [8]], dtype=torch.long)
y = torch.tensor([9.8765], dtype=torch.float)
square = pyg.data.Data(x=x, 
                      edge_index=edge_index, 
                      edge_attr=edge_attr,
                      y=y)

In [65]:
square

Data(edge_attr=[8, 1], edge_index=[2, 8], x=[4, 1], y=[1])

In [66]:
my_batch = pyg.data.Batch.from_data_list([house, square])

In [67]:
my_batch.edge_index

tensor([[0, 1, 0, 3, 1, 2, 2, 3, 2, 4, 3, 4, 5, 6, 5, 8, 6, 7, 7, 8],
        [1, 0, 3, 0, 2, 1, 3, 2, 4, 2, 4, 3, 6, 5, 8, 5, 7, 6, 8, 7]])

In [68]:
my_batch.x

tensor([[1.0000],
        [2.1000],
        [3.2000],
        [4.3000],
        [5.4000],
        [1.1000],
        [2.2000],
        [3.3000],
        [4.4000]])

In [69]:
my_batch.edge_attr

tensor([[ 7.],
        [ 7.],
        [11.],
        [11.],
        [ 8.],
        [ 8.],
        [ 6.],
        [ 6.],
        [ 5.],
        [ 5.],
        [ 4.],
        [ 4.],
        [ 6.],
        [ 6.],
        [90.],
        [90.],
        [ 7.],
        [ 7.],
        [ 8.],
        [ 8.]])

In [70]:
my_batch.y

tensor([12.3450,  9.8765])

In [71]:
my_batch.batch

tensor([0, 0, 0, 0, 0, 1, 1, 1, 1])